source 'https://rubygems.org'

gem 'pry'
gem 'rack', '1.6.13'
gem 'shotgun', '0.9.0'
gem 'rack-commonlogger'
gem 'rake'
# gem 'rack'
gem 'rack-test'
gem 'rspec'
gem 'rack-cors'
# gem 'shotgun'
gem "require_all"
gem "activerecord", "~> 5.2"
gem "sinatra-activerecord"
gem "sqlite3"
# gem "webrick", "~> 1.9"
gem 'webrick', '~> 1.7'